---

- hosts: all
  become: true
  tasks:
  - name: update the repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: update the repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"
  
  - name: install apache
    apt: 
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  